// Extended Emoji Dictionary
const emojiDictionary = {
    "love": "❤️",
    "pizza": "🍕",
    "happy": "😊",
    "cat": "🐱",
    "dog": "🐶",
    "coffee": "☕",
    "sun": "☀️",
    "moon": "🌙",
    "heart": "💖",
    "star": "⭐",
    "rain": "🌧️",
    "fire": "🔥",
    "car": "🚗",
    "tree": "🌳",
    "book": "📚",
    "computer": "💻",
    "music": "🎶",
    "dance": "💃",
    "man": "👨",
    "woman": "👩",
    "boy": "👦",
    "girl": "👧",
    "baby": "👶",
    "love_letter": "💌",
    "kiss": "💋",
    "hand": "✋",
    "raised_hand": "🙋‍♂️",
    "clap": "👏",
    "thumbs_up": "👍",
    "thumbs_down": "👎",
    "clap": "👏",
    "victory_hand": "✌️",
    "musical_note": "🎵",
    "guitar": "🎸",
    "headphones": "🎧",
    "camera": "📸",
    "earth": "🌍",
    "globe": "🌐",
    "earth_americas": "🌎",
    "earth_africa": "🌍",
    "flag": "🏁",
    "crossed_flags": "🎌",
    "soccer": "⚽",
    "basketball": "🏀",
    "tennis": "🎾",
    "baseball": "⚾",
    "flag_usa": "🇺🇸",
    "flag_india": "🇮🇳",
    "flag_canada": "🇨🇦",
    "flag_uk": "🇬🇧",
    "money_bag": "💰",
    "banknote": "💵",
    "shopping_cart": "🛒",
    "truck": "🚚",
    "airplane": "✈️",
    "rocket": "🚀",
    "train": "🚆",
    "bus": "🚌",
    "subway": "🚇",
    "hotdog": "🌭",
    "hamburger": "🍔",
    "fries": "🍟",
    "apple": "🍎",
    "banana": "🍌",
    "grapes": "🍇",
    "melon": "🍉",
    "cherry": "🍒",
    "strawberry": "🍓",
    "kiwi": "🥝",
    "lemon": "🍋",
    "avocado": "🥑",
    "carrot": "🥕",
    "onion": "🧅",
    "corn": "🌽",
    "tomato": "🍅",
    "potato": "🥔",
    "cucumber": "🥒",
    "bread": "🍞",
    "cheese": "🧀",
    "egg": "🥚",
    "meat": "🍖",
    "fish": "🐟",
    "cooking": "🍳",
    "shrimps": "🍤",
    "rice": "🍚",
    "noodles": "🍜",
    "sandwich": "🥪",
    "cake": "🍰",
    "ice_cream": "🍨",
    "pie": "🥧",
    "candy": "🍬",
    "lollipop": "🍭",
    "cookie": "🍪",
    "chocolate": "🍫",
    "popcorn": "🍿",
    "drink": "🍹",
    "beer": "🍺",
    "wine": "🍷",
    "cocktail": "🍸",
    "tropical_drink": "🍹",
    "hot_beverage": "☕",
    "champagne": "🍾",
    "tumbler": "🥂",
    "baby_bottle": "🍼",
    "beer_mug": "🍺",
    "wine_glass": "🍷",
    "cocktail_glass": "🍸",
    "sake": "🍶",
    "sushi": "🍣",
    "ramen": "🍜",
    "ice_cream_cone": "🍦",
    "birthday_cake": "🎂",
    "candy": "🍬",
    "clown_face": "🤡",
    "halloween": "🎃",
    "christmas_tree": "🎄",
    "gift": "🎁",
    "heart_eyes": "😍",
    "smile": "😊",
    "grinning": "😀",
    "sweat_smile": "😅",
    "smiling_eyes": "😊",
    "crying": "😢",
    "sad": "😞",
    "angry": "😡",
    "surprised": "😲",
    "disappointed": "😞",
    "blush": "😊",
    "wink": "😉",
    "kissing": "😘",
    "thinking": "🤔",
    "nerd": "🤓",
    "sunglasses": "😎",
    "face_with_head_bandage": "🤕",
    "face_with_thermometer": "🤒",
    "nauseated_face": "🤢",
    "sleepy": "😴",
    "sneezing": "🤧",
    "sleeping": "😴"
};

// Function to translate text to emojis
function translateToEmojis() {
    let inputText = document.getElementById("input-text").value.trim().toLowerCase();
    
    if (!inputText) {
        alert("Please type something to translate!");
        return;
    }

    let words = inputText.split(" ");
    let emojis = words.map(word => emojiDictionary[word] || word); // Map words to emojis

    // Display emojis in the output section
    let output = emojis.map(emoji => `<span title="${emoji}">${emoji}</span>`).join("");
    document.getElementById("emoji-output").innerHTML = output;
}

// Event listener for the Translate button
document.getElementById("translate-btn").addEventListener("click", translateToEmojis);

// Event listener for the Clear button
document.getElementById("clear-btn").addEventListener("click", function() {
    document.getElementById("input-text").value = "";
    document.getElementById("emoji-output").innerHTML = "";
});
